//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalTagger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://theaudiodb.com/api/v1/json/195003/searchtrack.php?s=")]
        public string AudioDBUrl {
            get {
                return ((string)(this["AudioDBUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.audioscrobbler.com/2.0/?method=track.search&api_key=")]
        public string LastFMTrackSearchUrl {
            get {
                return ((string)(this["LastFMTrackSearchUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MetaBrainz.MusicBrainz")]
        public string MBBaseUrl {
            get {
                return ((string)(this["MBBaseUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Zastai/MusicBrainz")]
        public string MBUserAgentUrl {
            get {
                return ((string)(this["MBUserAgentUrl"]));
            }
            set {
                this["MBUserAgentUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2.0.0")]
        public string MBVersion {
            get {
                return ((string)(this["MBVersion"]));
            }
            set {
                this["MBVersion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://musicbrainz.org/ws/2/recording/?query=")]
        public string MBRecordingUrl {
            get {
                return ((string)(this["MBRecordingUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://developer.spotify.com/web-api/")]
        public string SpotifyBaseAddress {
            get {
                return ((string)(this["SpotifyBaseAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.discogs.com/oauth/request_token")]
        public string DiscogsRequestTokenUrl {
            get {
                return ((string)(this["DiscogsRequestTokenUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.discogs.com/oauth/authorize")]
        public string DiscogsAuthorizeUrl {
            get {
                return ((string)(this["DiscogsAuthorizeUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.discogs.com/oauth/access_token")]
        public string DiscogsAccessTokenUrl {
            get {
                return ((string)(this["DiscogsAccessTokenUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.audioscrobbler.com/2.0/?method=album.getinfo&api_key=")]
        public string LastFMAlbumGetInto {
            get {
                return ((string)(this["LastFMAlbumGetInto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.audioscrobbler.com/2.0/?method=track.getinfo&api_key=")]
        public string LastFMTrackGetInfo {
            get {
                return ((string)(this["LastFMTrackGetInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&api_key=")]
        public string LastFMArtistTopAlbums {
            get {
                return ((string)(this["LastFMArtistTopAlbums"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://musicbrainz.org/ws/2/release/?query=")]
        public string MBReleaseUrl {
            get {
                return ((string)(this["MBReleaseUrl"]));
            }
            set {
                this["MBReleaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.rhapsody.com/v2/search?q=%SEARCHTERM%&include=genres&type=track&limit=" +
            "%LIMIT%&apikey=%APIKEY%")]
        public string NapsterURL {
            get {
                return ((string)(this["NapsterURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://itunes.apple.com/search?term=%SEARCHTERM%&media=music&limit=1")]
        public string ITunesURL {
            get {
                return ((string)(this["ITunesURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.deezer.com/search?q=artist:%SEARCHARTIST%track:%SEARCHTITLE%&limit=%LI" +
            "MIT%&order=RANKING")]
        public string DeezerURL {
            get {
                return ((string)(this["DeezerURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://secure.galiboo.com/api/metadata/tracks/search/?token=%APIKEY%&track=%SEARC" +
            "HTITLE%")]
        public string GalibooUrl {
            get {
                return ((string)(this["GalibooUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://secure.galiboo.com/api/metadata/tracks/search/?token=%APIKEY%&artist=%SEAR" +
            "CHARTIST%")]
        public string GalibooUrlArtist {
            get {
                return ((string)(this["GalibooUrlArtist"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.genius.com/search?q=%SEARCHTERM%&access_token=%APIKEY%&text_format=pl" +
            "ain")]
        public string GeniusURL {
            get {
                return ((string)(this["GeniusURL"]));
            }
        }
    }
}
